### ISSUE TITLE
SyntaxError: keyword argument repeated

### ISSUE THREAD

**Issue by plbaldoni** [jsxlei/SCALE#15]
I am having issues to install/use SCALE. First, I created a conda environment and installed SCALE:

```
conda create -n SCALE python=3.6 pytorch
conda activate SCALE

git clone git://github.com/jsxlei/SCALE.git
cd SCALE
python setup.py install
```

It seems the installation went smoothly as I did not get any error messages. However, by running SCALE.py I get the following error:

```
  File "/nas/longleaf/home/baldoni/SCALE/SCALE.py", line 165
    save=os.path.join(outdir, 'emb_{}.pdf'.format(args.emb)), save=os.path.join(outdir, 'emb_{}.txt'.format(args.emb)))
                                                             ^
SyntaxError: keyword argument repeated
```

Am I missing something here?

I appreciate your help.
Pedro

**Comment by jsxlei** [comment]
This error has been fixed, you can git clone the update code and install it again. Thanks for pointing out this error.

**Comment by plbaldoni** [comment]
Great, thanks!
