### ISSUE TITLE
can't download the dataset from the link

### ISSUE THREAD

**Issue by yingyuan830** [jsxlei/SCALE#22]
I 'd like to use the dataset, but can not download from the given link, could you please help me ? Thanks

**Comment by jsxlei** [comment]
Hi, copy the download_link then "wget download_link --no-check-certificate" or other downloader. Just click the link won't automatically download it. e.g. wget https://zhanglab.net/SCALE_SOURCE_DATA/Forebrain.h5ad --no-check-certificate

**Comment by yingyuan830** [comment]
solved, thanks!

**Comment by litxiaoyao** [comment]
It went 404 and can't be solved using --no-check-certificate

**Comment by jsxlei** [comment]
Use the alternate link https://www.dropbox.com/sh/9oieqeogmfj7qrc/AACbaRnGpTpvxcFO7db5yDY5a?dl=0 .

**Comment by litxiaoyao** [comment]
Thanks!
