### ISSUE TITLE
KeyError: 'imputed' or 'binary' using the new version of SCALE

### ISSUE THREAD

**Issue by litxiaoyao** [jsxlei/SCALE#27]
I have successfully runed --impute, and successfully got the adata.h5ad file.
However, it cracked when calling adata.obsm['imputed']
![image](https://github.com/jsxlei/SCALE/assets/68361174/748526ef-e74f-481e-885b-9456954e4f63)

**Comment by jsxlei** [comment]
It should have. You can use the latest version of SCALE and use option --binary. This should work. You can check the keys in adata.obsm to see if there is an 'impute' or 'binary' exist. Let me know if you have any question.

**Comment by litxiaoyao** [comment]
> It should have. You can use the latest version of SCALE and use option --binary. This should work. You can check the keys in adata.obsm to see if there is an 'impute' or 'binary' exist. Let me know if you have any question.

Thanks for your reply, lei.
I have installed SCALE by pip, and I have tried using --binary but it didn't work and retain the same as --impute. So should I reinstall SCALE using git clone?

**Comment by jsxlei** [comment]
Try this command to install: pip install git+https://github.com/jsxlei/SCALE.git

**Comment by litxiaoyao** [comment]
Thank you very much lei!! It works when using this version of SCALE and using --impute parameter rather than --binary to get both keys 'impute' or 'binary' in adata.obsm. Besides, the key name is 'impute' rather than 'imputed' in the README.md.
