### ISSUE TITLE
data availability

### ISSUE THREAD

**Issue by lihaicheng7003** [jsxlei/SCALE#28]
The link to the data availability in the tutorial is no longer accessible. Would it be possible to provide an updated link or alternative access to the data? thanks

**Comment by jsxlei** [comment]
Hi, you can use this link https://www.dropbox.com/sh/9oieqeogmfj7qrc/AACbaRnGpTpvxcFO7db5yDY5a?dl=0 to download the data.

**Comment by WhatMelonGua** [comment]
![image](https://github.com/jsxlei/SCALE/assets/92420346/d872c9b7-ddb8-4bb6-a5b1-b0755d16bb84)
I got that, too
Hope fixed, such as update the link

**Comment by WhatMelonGua** [comment]
> Hi, you can use this link https://www.dropbox.com/sh/9oieqeogmfj7qrc/AACbaRnGpTpvxcFO7db5yDY5a?dl=0 to download the data.

Thank you for your Link! That's helpful!

**Comment by lihaicheng7003** [comment]
thanks
