### ISSUE TITLE
Running Forebrain turorial

### ISSUE THREAD

**Issue by Pacomito** [jsxlei/SCALE#6]
Hi @jsxlei  ! 
Thanks for the nice tool & article,
I would like to try out your tool, the installation step worked fine but running the tutorial I came across an error : 

`python3.6 SCALE.py -d Forebrain/data.txt -k 8 --impute`

> Loading  data ...
> Original data contains 2088 cells x 678 peaks
> Finished loading takes 0.00 min
> /usr/local/lib/python3.6/dist-packages/scipy/sparse/compressed.py:213: RuntimeWarning: invalid value encountered in greater
>   res = self._with_data(op(self.data, other), copy=True)
> /usr/local/lib/python3.6/dist-packages/scipy/sparse/compressed.py:213: RuntimeWarning: invalid value encountered in greater
>   res = self._with_data(op(self.data, other), copy=True)
> Traceback (most recent call last):
>   File "SCALE.py", line 77, in <module>
>     transpose=args.transpose, transforms=[normalizer.fit_transform])
>   File "/home/pprompsy/SCALE-master/scale/dataset.py", line 42, in __init__
>     self.data = transform(self.data)
>   File "/usr/local/lib/python3.6/dist-packages/sklearn/base.py", line 553, in fit_transform
>     return self.fit(X, **fit_params).transform(X)
>   File "/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/data.py", line 907, in fit
>     return self.partial_fit(X, y)
>   File "/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/data.py", line 926, in partial_fit
>     force_all_finite='allow-nan')
>   File "/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py", line 558, in check_array
>     context))
> ValueError: Found array with 0 feature(s) (shape=(1, 0)) while a minimum of 1 is required by MaxAbsScaler.

Thanks in advance,
Pacome

**Comment by jsxlei** [comment]
Hi Pacome,
The Forebrain dataset provided is supposed to contain 2088 cells x 11286 peaks (double checked), but your post info said your input data is 2088 cells x 678 peaks, I think it maybe the input data has not completely downloaded, please check out the input data.
Lei

**Comment by Pacomito** [comment]
It all works fine, 
Thanks again
